name: Deploy DalatOS AI
on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inject API Key
        env:
          MY_SECRET_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          find . -name "index.html" -exec perl -i -pe 's/GEMINI_API_KEY/$ENV{MY_SECRET_KEY}/g' {} +
          find . -name "index.html" -exec perl -i -pe 's/__API_KEY_PLACEHOLDER__/$ENV{MY_SECRET_KEY}/g' {} +
          echo "✅ Đã thay thế xong giá trị thực vào file!"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . 
          branch: gh-pages
          clean: true
